-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 15:47:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema srdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROLE` (
  `ROLE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '角色编号',
  `ROLE_NAME` VARCHAR(128) NULL COMMENT '角色名',
  `ROLE_TITLE` VARCHAR(64) NULL,
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `REMARK` VARCHAR(256) NULL,
  `CREATOR` VARCHAR(64) NULL,
  PRIMARY KEY (`ROLE_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(64) NOT NULL COMMENT '用户名',
  `USER_PWD` VARCHAR(256) NOT NULL COMMENT '用户密码',
  `PHONE` VARCHAR(64) NULL COMMENT '用户手机号',
  `EMAIL` VARCHAR(64) NULL COMMENT '用户邮箱',
  `NAME` VARCHAR(64) NULL COMMENT '姓名',
  `POLICE_CODE` VARCHAR(64) NULL COMMENT '警号',
  `IDCARD` VARCHAR(64) NULL COMMENT '证件号码',
  `POLICE` VARCHAR(32) NULL COMMENT '派出所编码',
  `AREA_CODE` VARCHAR(64) NULL COMMENT '区域编码',
  `ACTION` VARCHAR(64) NULL COMMENT '默认页面',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT now() COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NULL COMMENT '修改时间',
  `LOGIN_LAST` DATETIME NULL COMMENT '最后登录时间',
  `LOGIN_TOTAL` INT NULL DEFAULT 0 COMMENT '总登陆次数',
  `USER_TYPE` INT NULL DEFAULT 2 COMMENT '用户类型1：管理账号 2：普通用户',
  `STATUS` INT NULL DEFAULT 1 COMMENT '用户状态 1为启用 0为禁用',
  `CREATOR` VARCHAR(64) NULL COMMENT '创建者',
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC),
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `USER_ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USER_ROLES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE_ID` INT NULL COMMENT '角色编号',
  `USER_ID` INT NULL COMMENT '用户名',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `MENU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MENU` (
  `MENU_ID` INT NOT NULL AUTO_INCREMENT COMMENT '菜单编号',
  `MENU_NAME` VARCHAR(64) NOT NULL COMMENT '菜单名',
  `MENU_TITLE` VARCHAR(64) NULL COMMENT '显示标题',
  `PARENT_NAME` VARCHAR(64) NOT NULL COMMENT '上级菜单',
  `ACTION` VARCHAR(256) NULL COMMENT '请求地址',
  `ODER_BY` INT NULL DEFAULT 0 COMMENT '排序',
  `STATUS` INT NULL DEFAULT 1 COMMENT '状态1为可用，0为不可用',
  `AREA` VARCHAR(32) NULL COMMENT '区域',
  `ICON` VARCHAR(64) NULL COMMENT '图标',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATOR` VARCHAR(64) NULL COMMENT '创建者',
  `MENU_FUNCTION` VARCHAR(64) NULL COMMENT '点击菜单触发函数',
  `MENU_STYLE` VARCHAR(512) NULL COMMENT '菜单样式',
  `MENU_STYLE_CLASS` VARCHAR(64) NULL COMMENT '菜单样式名',
  PRIMARY KEY (`MENU_ID`),
  UNIQUE INDEX `MENU_NAME_UNIQUE` (`MENU_NAME` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `ROLE_MENUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROLE_MENUS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MENU_ID` INT NOT NULL COMMENT '菜单编号',
  `ROLE_ID` INT NOT NULL COMMENT '角色编号',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOG` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATER` VARCHAR(64) NULL COMMENT '操作用户名称',
  `REQUEST_URL` VARCHAR(512) NULL COMMENT 'URL',
  `REQUEST_TIME` DATETIME NULL COMMENT '日志生成时间',
  `REQUEST_METHOD` VARCHAR(64) NULL COMMENT '提交类型POST GET等',
  `REQUEST_PARAM` VARCHAR(512) NULL COMMENT '请求参数',
  `EXECUTE_TIME` INT NULL COMMENT '执行时间',
  `HTTP_CODE` INT NULL COMMENT 'HTTP响应状态',
  `USER_AGENT` VARCHAR(256) NULL COMMENT '浏览器类型',
  `CLIENT_IP` VARCHAR(32) NULL COMMENT 'IP地址',
  `DESCRIPTION` VARCHAR(512) NULL COMMENT '详细描述，如方法名称',
  `ERROR_MESSAGE` VARCHAR(256) NULL COMMENT '异常信息',
  `OPERATE_TYPE` INT NULL COMMENT '1:新增，2：删除，3：修改，4：查询，98:登录，99：其他',
  `MOUDLE_NAME` VARCHAR(64) NULL COMMENT '操作模块名称',
  `MENU_NAME` VARCHAR(64) NULL COMMENT '操作菜单名称',
  PRIMARY KEY (`ID`),
  INDEX `LOG_OPERATE_INDEX` (`OPERATE_TYPE` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `AREA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AREA` (
  `ID` INT(22) NOT NULL COMMENT '区域编号',
  `AREA_CODE` VARCHAR(12) NOT NULL,
  `AREA_NAME` VARCHAR(64) NOT NULL COMMENT '区域名称',
  `P_AREA_CODE` VARCHAR(12) NULL DEFAULT NULL COMMENT '父级编号',
  `REMARK` VARCHAR(70) NULL DEFAULT NULL COMMENT '备注',
  `SORT` INT(2) NULL DEFAULT NULL COMMENT '区域排序',
  `FLAG` INT(2) NULL DEFAULT '0' COMMENT '是否删除  0未删除  1已删除',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `POLICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POLICE` (
  `ID` INT(22) NOT NULL,
  `POLICE_CODE` VARCHAR(12) NULL DEFAULT NULL COMMENT '派出所编号',
  `POLICE_NAME` VARCHAR(30) NULL DEFAULT NULL COMMENT '派出所名称',
  `POLICE_NAME_PINYIN` VARCHAR(255) NULL DEFAULT NULL COMMENT '派出所拼音',
  `P_POLICE_CODE` VARCHAR(12) NULL DEFAULT NULL COMMENT '父级派出所编号',
  `REMARK` VARCHAR(70) NULL DEFAULT NULL COMMENT '备注',
  `AREA_CODE` VARCHAR(12) NULL DEFAULT NULL COMMENT '区域编号',
  `SORT` INT(3) NULL DEFAULT NULL COMMENT '派出所排序',
  `FLAG` INT(2) NULL DEFAULT '0' COMMENT '是否删除 0未删除  1已删除',
  `POINT_X` VARCHAR(20) NULL DEFAULT NULL COMMENT '经度',
  `POINT_Y` VARCHAR(20) NULL DEFAULT NULL COMMENT '纬度',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `DICT_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DICT_TYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE_NAME` VARCHAR(45) NULL COMMENT '字典名称',
  `TYPE_CREATETIME` DATETIME NULL DEFAULT now() COMMENT '创建时间',
  `TYPE_ID` INT NOT NULL COMMENT '类型编号',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `TYPE_ID_UNIQUE` (`TYPE_ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 50000;


-- -----------------------------------------------------
-- Table `DICT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DICT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DICT_NAME` VARCHAR(64) NULL COMMENT '字典名称',
  `DICT_ID` VARCHAR(128) NOT NULL COMMENT '字典ID',
  `TYPE_ID` INT NOT NULL COMMENT '所属类型ID',
  PRIMARY KEY (`ID`),
  INDEX `DICT_TYPE_INDEX` (`TYPE_ID` ASC, `DICT_ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 50000;


-- -----------------------------------------------------
-- Table `SCRIPT_SQLLOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCRIPT_SQLLOG` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATE_TIME` DATETIME NOT NULL DEFAULT now() COMMENT '创建时间',
  `SQL_TYPE` VARCHAR(64) NOT NULL COMMENT '类型schema、data',
  `SQL_VERSION` VARCHAR(32) NOT NULL COMMENT '版本',
  `SQL_SCRIPTS` VARCHAR(512) NULL COMMENT '脚本',
  `EXECUTE_TIME` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1000;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ROLE`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `ROLE` (`ROLE_ID`, `ROLE_NAME`, `ROLE_TITLE`, `CREATE_TIME`, `REMARK`, `CREATOR`) VALUES (1, 'admin', '系统管理员', DEFAULT, '系统维护', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `USERS`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `USERS` (`USER_ID`, `USER_NAME`, `USER_PWD`, `PHONE`, `EMAIL`, `NAME`, `POLICE_CODE`, `IDCARD`, `POLICE`, `AREA_CODE`, `ACTION`, `CREATE_TIME`, `UPDATE_TIME`, `LOGIN_LAST`, `LOGIN_TOTAL`, `USER_TYPE`, `STATUS`, `CREATOR`) VALUES (1, 'admin', '$shiro1$SHA-256$500000$sUxthiGVcfPJ0tW+j+CrhQ==$rh04dJWzd23dSBH4JI+B8254hW0QPhhXR69aCqN9JRA=', NULL, 'soupport@sinnren.com', 'sinnren admin', NULL, NULL, NULL, NULL, '/admin', DEFAULT, NULL, NULL, NULL, 1, 1, NULL);
INSERT INTO `USERS` (`USER_ID`, `USER_NAME`, `USER_PWD`, `PHONE`, `EMAIL`, `NAME`, `POLICE_CODE`, `IDCARD`, `POLICE`, `AREA_CODE`, `ACTION`, `CREATE_TIME`, `UPDATE_TIME`, `LOGIN_LAST`, `LOGIN_TOTAL`, `USER_TYPE`, `STATUS`, `CREATOR`) VALUES (DEFAULT, 'test', '$shiro1$SHA-256$500000$sUxthiGVcfPJ0tW+j+CrhQ==$rh04dJWzd23dSBH4JI+B8254hW0QPhhXR69aCqN9JRA=', NULL, 'soupport@sinnren.com', 'sinnren test', NULL, NULL, NULL, NULL, '/main', DEFAULT, NULL, NULL, NULL, 1, 1, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `USER_ROLES`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `USER_ROLES` (`ID`, `ROLE_ID`, `USER_ID`) VALUES (1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `MENU`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'sysmanager', '系统管理', 'root', '/admin', 1, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'usermanager', '用户管理', 'sysmanager', '/admin/user/list', 1, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'adduser', '新增用户', 'usermanager', '/admin/user/add', 1, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'updateuser', '修改用户', 'usermanager', '/admin/user/edit', 2, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'deleteuser', '删除用户', 'usermanager', '/admin/user/delete', 3, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'rolemanager', '角色管理', 'sysmanager', '/admin/role/list', 3, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'addrole', '新增角色', 'rolemanager', '/admin/role/add', 1, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'updaterole', '修改角色', 'rolemanager', '/admin/role/edit', 2, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'delrole', '删除角色', 'rolemanager', '/admin/role/delete', 3, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'menumanager', '菜单管理', 'sysmanager', '/admin/menu/list', 2, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'addmenu', '新增菜单', 'menumanager', '/admin/menu/add', 1, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'updatemenu', '修改菜单', 'menumanager', '/admin/menu/edit', 2, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'deletemenu', '删除菜单', 'menumanager', '/admin/menu/delete', 3, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'logmanager', '日志管理', 'sysmanager', '/admin/log/list', 4, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'keywordmanager', '词库管理', 'sysmanager', '/fierace/keyword-manger', 2, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'jobmanager', '任务管理', 'root', NULL, 2, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'kettleJobManager', '数据工具', 'jobmanager', '/kettleJob/jobList', 2, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'jobRunManager', '系统任务', 'jobmanager', '/job/jobRunManager', 1, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);
INSERT INTO `MENU` (`MENU_ID`, `MENU_NAME`, `MENU_TITLE`, `PARENT_NAME`, `ACTION`, `ODER_BY`, `STATUS`, `AREA`, `ICON`, `CREATE_TIME`, `CREATOR`, `MENU_FUNCTION`, `MENU_STYLE`, `MENU_STYLE_CLASS`) VALUES (DEFAULT, 'bimanage', '智能分析', 'sysmanager', '/bi/bi-manager', 5, 1, NULL, NULL, DEFAULT, 'admin', NULL, NULL, NULL);

COMMIT;

